### ISSUE TITLE
Gem is missing from Ruby Gems

### ISSUE THREAD

**Issue by jazzdan** [honeycombio/rack-honeycomb#1]
```
> gem install rack-honey
ERROR:  Could not find a valid gem 'rack-honey' (>= 0) in any repository
```

https://rubygems.org/gems/rack-honey

Is this intentional? :)

**Comment by samstokes** [comment]
Oops, thanks for pointing that out! Fixed now: https://rubygems.org/gems/rack-honeycomb

We also renamed the gem (and the repo) to rack-honeycomb for consistency with other Rack middlewares.

**Comment by jazzdan** [comment]
Thanks for the heads up @samstokes!
