### ISSUE TITLE
Provide the means for filtering/masking named params

### ISSUE THREAD

**Issue by revgum** [honeycombio/rack-honeycomb#13]
Login credentials are showing up in traces related to our login form. This gem doesn't currently seem to support a configuration for filtering or masking values for specific param names.

**Comment by martin308** [comment]
@revgum you're correct this is a missing feature. We have just today pushed a change (in `0.5.0`) to this gem that removes the params collection due to some other issues but that should 'solve' this for now. We are definitely thinking about how best to accomplish this though

**Comment by martin308** [comment]
This is supported in `v1.0.0` of the beeline now with a `presend_hook` to scrub data
