### ISSUE TITLE
`request.route` can report incorrect route when multiple routes match request method+path

### ISSUE THREAD

**Issue by bjeanes** [honeycombio/rack-honeycomb#14]
I don't know if this in the gem or on the Honeycomb servers, but these two things definitely do not match:

![2019-03-12 at 4 20 pm](https://user-images.githubusercontent.com/2560/54176591-933ca180-44e3-11e9-8311-7b38f1169a22.png)

```
$ rake routes | grep review_studies/:id
 edit_review_study  GET     /reviews/:review_id/review_studies/:id/edit(.:format)  reviews/studies#edit
      review_study  GET     /reviews/:review_id/review_studies/:id(.:format)       reviews/studies#show
                    PATCH   /reviews/:review_id/review_studies/:id(.:format)       reviews/studies#update
                    PUT     /reviews/:review_id/review_studies/:id(.:format)       reviews/studies#update
                    DELETE  /reviews/:review_id/review_studies/:id(.:format)       reviews/studies#destroy
```

**Comment by martin308** [comment]
@bjeanes thanks for reporting this! If I understand you correctly, the repro for this is having duplicate routes? We are asking the rails router for the path [here](https://github.com/honeycombio/rack-honeycomb/blob/master/lib/rack/honeycomb/middleware.rb#L165), if you can confirm that is the repro then I can dig into this further

**Comment by bjeanes** [comment]
Yeah that would be my understanding. I'm surprised `router.recognize` doesn't return the correct route, given it's probably how Rails translates a request into a controller+action anyway 🤔. Does it perhaps return multiple candidates?

The pattern for the route that is being returned does _match_ the path of the request (because `:id` is unconstrained and so can also match `'included'`), but the route precedence should mean the other route is matched first.

**Comment by bjeanes** [comment]
The `recognize` method actually mutates the request.env when called: https://github.com/rails/rails/blob/8b3d2d1a717d795dd443d37ab762f82c2bccd6c1/actionpack/lib/action_dispatch/journey/router.rb#L64-L74

**Comment by bjeanes** [comment]
(Whoop sorry, actually submitted comment early...)

It looks like `recognize` calls `find_routes` which does yield _multiple_ times. It's quite possible that block in Honeycomb is being called multiple times, which means that the `formatted_route` is set to the _last_ invocation of that block.

Perhaps, instead, use `find_routes` directly so that the `env` is not mutated, and instead of using `each` use `first` to get the first match (which, I'd wager, is the correct match).

**Comment by bjeanes** [comment]
Ah `find_routes` is private, so perhaps not. However:

``` ruby
>> routes.router.send(:find_routes, request).count
=> 2
```

**Comment by bjeanes** [comment]
I've confirmed the first one is the correct one in my case. I think simply adding a `next if formatted_route` to top of block would fix this. Alternatively, `break` at the end of the block might work...

**Comment by martin308** [comment]
@bjeanes I think I have a the fix for this, but I'm having trouble reproducing it in a test. Do you think you could plug something like your routing setup into [this test](https://github.com/honeycombio/rack-honeycomb/blob/master/spec/middleware/rails_spec.rb#L22) and see if you can reproduce it?

**Comment by bjeanes** [comment]
Hey sorry @martin308. We hit the end of our Honeycomb trial and decided not to continue with it. I don't think I'll be able to help get this over the line in the context of our app, but I'd be happy to try help another way, if you can think of one.
